let modeloFilmes = [
  {
    id: 1,
    name: "Aladin",
    category: "Ação/Aventura",
    duration: "2h05",
    img: "img/filme1.png",
    link: "https://www.youtube.com/embed/PRyOvcOhtms",
    synopsis: "Aladin é um cara e é isso aí, teste 1",
    background: "img/background-filmes/aladdin.png",
  },
  {
    id: 2,
    name: "Capitã Marvel",
    category: "Aventura/Ação",
    duration: "2h45",
    img: "img/filme2.png",
    link: "https://www.youtube.com/embed/PRyOvcOhtms",
    synopsis: "O mina gostosa",
    background: "img/background-filmes/capitain-marvel.png",
  },
  {
    id: 3,
    name: "Homem Aranha, de volta ao lar",
    category: "Aventura/Ação",
    duration: "2h45",
    img: "img/filme3.png",
    link: "https://www.youtube.com/watch?v=g6ng8iy-l0U",
    synopsis: "Aladin é um cara e é isso aí, teste 1",
    background: "img/background-filmes/spider-man-homecomming.png",
  },
  {
    id: 4,
    name: "Homem de Ferro 3",
    category: "Aventura/Ação",
    duration: "2h45",
    img: "img/filme4.png",
    link: "https://www.youtube.com/watch?v=g6ng8iy-l0U",
    synopsis: "Aladin é um cara e é isso aí, teste 1",
    background: "img/background-filmes/iron-man3-v2.png",
  },
  {
    id: 5,
    name: "Vingadores Ultimato",
    category: "Aventura/Ação",
    duration: "2h45",
    img: "img/filme5.png",
    link: "https://www.youtube.com/watch?v=g6ng8iy-l0U",
    synopsis: "Aladin é um cara e é isso aí, teste 1",
    background: "img/background-filmes/avengers-ultimate.png",
  },
  {
    id: 6,
    name: "Vingadores",
    category: "Aventura/Ação",
    duration: "2h45",
    img: "img/filme6.png",
    link: "https://www.youtube.com/watch?v=g6ng8iy-l0U",
    synopsis: "Aladin é um cara e é isso aí, teste 1",
    background: "img/background-filmes/avengers.png",
  },
];
